cofig/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.categorias.views import CategoryListView, listar_categorias
from core.erp.views.productos.views import ProductListView
# from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

from core.erp.views.views import IndexView, view_general, view_productos

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', IndexView.as_view(), name='index'),
    path('', view_general, name='index'),
    path('<id>/', view_productos, name='product_view')

    # path('', listar_categorias, name='index'),
    # path('erp/', include('core.erp.urls'), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.categorias.views import *
from core.erp.views.detalles.views import ver_productos
# from core.erp.views.detalles.views import ver_productos, view_general
# from core.erp.views.clientes.views import *
# from core.erp.views.dashboard.views import DashboardView
from core.erp.views.productos.views import *
# from core.erp.views.tests.views import TestView

app_name = 'erp'

urlpatterns = [

    #Catalogo
    path('', listar_categorias, name='category_list'),
    # path('detalles/<id>', ver_productos, name='product_view'),

    # path('<nombre>/', listar_productos, name='product_list'),
    # path('b', buscar_productos, name='buscar'),
    # path('detail/<id>/', ver_productos, name='product_view'),
    # path('total/general/', view_general, name='product_view_general'),


    # Categorias
    # path('categorias/list/', CategoryListView.as_view(), name='category_list'),

    # path('categorias/add/', CategoryCreateView.as_view(), name='category_create'),
    # path('categorias/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    # path('categorias/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # path('categorias/list/', search, name='category_list'),

    # path('categorias/form/', CategoryFormView.as_view(), name='category_form'),

    # Clientes
    # path('clientes/list/', ClientListView.as_view(), name='client_list'),
    # path('clientes/add/', ClientCreateView.as_view(), name='client_create'),
    # path('clientes/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    # path('clientes/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    # Productos
    # path('productos/list/', ProductListView.as_view(), name='product_list'),

    # path('productos/add/', ProductCreateView.as_view(), name='product_create'),
    # path('productos/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    # path('productos/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),


    # Home
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # Tests
    # path('test/', TestView.as_view(), name='tests'),
]

core/erp/views/categorias/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView

from core.erp.forms import CategoryForm
from core.erp.mixins import  ValidatePermissionRequiredMixin
from core.erp.models import *


# MANERA CLASE
class CategoryListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    permission_required = 'erp.view_category'
    model = Category
    template_name = 'categorias/list.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # sobreescribir metodo post
    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Category.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    # PASA LOS DATOS A LA VISTA
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Listado de Categorias"
        context['create_url'] = reverse_lazy('erp:category_create')
        context['list_url'] = reverse_lazy('erp:category_list')
        context['entity'] = 'Categorias'
        context['categorias'] = Category.objects.all()
        return context


def listar_categorias(request):
    template_name = 'productos/list.html'
    cat = Category.objects.first()
    productos = Product.objects.filter(active=True, cate=cat)
    categorias = Category.objects.filter(active=True)
    context = {"productos": productos, "categorias": categorias}
    return render(request, template_name, context)

#
# class CategoryListView2(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
#     permission_required = 'erp.view_category'
#     model = Category
#     template_name = 'list2.html'
#
#     @method_decorator(csrf_exempt)
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)
#
#     # sobreescribir metodo post
#     def post(self, request, *args, **kwargs):
#         data = {}
#         try:
#             action = request.POST['action']
#             if action == 'searchdata':
#                 data = []
#                 for i in Category.objects.all():
#                     data.append(i.toJSON())
#             else:
#                 data['error'] = 'Ha ocurrido un error'
#         except Exception as e:
#             data['error'] = str(e)
#         return JsonResponse(data, safe=False)
#
#     # PASA LOS DATOS A LA VISTA
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['title'] = "Listado de Categorias"
#         context['create_url'] = reverse_lazy('erp:category_create')
#         context['list_url'] = reverse_lazy('erp:category_list')
#         context['entity'] = 'Categorias'
#         context['categorias'] = Category.objects.all()
#         return context


class CategoryCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'categorias/create.html'
    permission_required = 'erp.add_category'
    success_url = reverse_lazy('erp:category_list')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opcion'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    # PASA LOS DATOS A LA VISTA
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Creacion de una categoria"
        context['entity'] = 'Categorias'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class CategoryUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = 'erp.change_category'
    model = Category
    form_class = CategoryForm
    template_name = 'categorias/create.html'
    success_url = reverse_lazy('erp:category_list')
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opcion'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Edicion de una categoria"
        context['entity'] = 'Categorias'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        return context


class CategoryDeleteView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DeleteView):
    permission_required = 'erp.delete_category'
    model = Category
    template_name = 'categorias/delete.html'
    success_url = reverse_lazy('erp:category_list')
    url_redirect = success_url

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eliminacion de una categoria"
        context['entity'] = 'Categorias'
        context['list_url'] = self.success_url
        return context

core/erp/views/detalles/views.py
from django.shortcuts import render

from core.erp.models import *


def ver_productos(request, id):
    template_name = 'detalles/view.html'
    productos = Product.objects.filter(active=True, id=id)
    categorias = Category.objects.filter(active=True)

    listado = []
    for pro in productos:
        ingredientes = []
        for ingre in pro.ing.all():
            ingredientes.append(ingre.name)
        item = {
            'producto': {
                'id': pro.id,
                'name': pro.name,
                'get_image': pro.get_image,
                'desc': pro.desc,
                'pvp': pro.pvp,
                'cate': pro.cate,
                # 'ingre': pro.ing.all(),
                'ingre': ingredientes,
            }
        }
        listado.append(item)

    context = {"productos": listado, "categorias": categorias}
    return render(request, template_name, context)


def view_general(request):
    template_name = 'detalles/view_total.html'
    # prod = Product.objects.filter(active=True)
    categorias = Category.objects.filter(active=True)
    total = []
    for c in categorias:
        productos = Product.objects.filter(active=True, cate=c.id)
        # TENGO TODOS LOS PROD PARA LA CAT DE ARRIBA
        listado = []
        for pro in productos:
            # ingredientes = Ingredient.objects.filter(active=True)
            # pr = Product.objects.filter(active=True, ing__id=ingredientes.id)
            # AGREGAR LISTADO DE INGREDIENTES
            ingredientes = []
            for ingre in pro.ing.all():
                ingredientes.append(ingre.name)
            # ingr = []
            # for ing in ingredientes:
            #     ingr.append(ing)
            # # GUARDAR EL PRODUCTO
            item = {
                'producto': {
                    'id': pro.id,
                    'name': pro.name,
                    'get_image': pro.get_image,
                    'desc': pro.desc,
                    'pvp': pro.pvp,
                    'cate': pro.cate,
                    # 'ingre': pro.ing.all(),
                    'ingre': ingredientes,
                }
            }
            listado.append(item)
        item1 = {
            'categ': {
                'cat': c.name,
                'cat_prod': listado
            }
        }
        # Supuestamente aqui tengo los item1
        # las categorias como categ dentro de los item
        # y dentro la categoria y un listado de sus productos
        if len(listado) != 0:
            total.append(item1)

    context = {'total_cat_pro': total, 'categorias': categorias}
    return render(request, template_name, context)

core/erp/views/views.py
from django.contrib.messages.storage import session
from django.shortcuts import render
from django.views.generic import TemplateView
from django.urls import reverse_lazy

from core.erp.models import *


class IndexView(TemplateView):
    template_name = 'body.html'


def view_general(request):
    template_name = 'body.html'
    # prod = Product.objects.filter(active=True)
    categorias = Category.objects.filter(active=True)
    total = []
    for c in categorias:
        productos = Product.objects.filter(active=True, cate=c.id)
        # TENGO TODOS LOS PROD PARA LA CAT DE ARRIBA
        listado = []
        for pro in productos:
            # ingredientes = Ingredient.objects.filter(active=True)
            # pr = Product.objects.filter(active=True, ing__id=ingredientes.id)
            # AGREGAR LISTADO DE INGREDIENTES
            ingredientes = []
            agregados = []
            for ingre in pro.ing.all():
                ingredientes.append(ingre.name)
            for agreg in pro.agre.all():
                agregados.append(agreg.name)
            # # GUARDAR EL PRODUCTO
            item = {
                'producto': {
                    'id': pro.id,
                    'name': pro.name,
                    'get_image': pro.get_image,
                    'desc': pro.desc,
                    'pvp': pro.pvp,
                    'cate': pro.cate,
                    'ingre': ingredientes,
                    'agreg': agregados,
                }
            }
            listado.append(item)
        item1 = {
            'categ': {
                'cat': c.name,
                'desc': c.desc,
                'cat_prod': listado
            }
        }
        # Supuestamente aqui tengo los item1
        # las categorias como categ dentro de los item
        # y dentro la categoria y un listado de sus productos
        if len(listado) != 0:
            total.append(item1)

    context = {'todo_prod': total, 'categorias': categorias}
    return render(request, template_name, context)


def view_productos(request, id):
    template_name = 'view_product.html'
    # prod = Product.objects.filter(active=True)
    categorias = Category.objects.filter(active=True)
    productos = Product.objects.filter(active=True, id=id)
    # TENGO TODOS LOS PROD PARA LA CAT DE ARRIBA
    listado = []
    for pro in productos:
        # AGREGAR LISTADO DE INGREDIENTES
        ingredientes = []
        agregados = []
        for ingre in pro.ing.all():
            ingredientes.append(ingre.name)
        for agreg in pro.agre.all():
            agregados.append(agreg)
        # # GUARDAR EL PRODUCTO
        item = {
            'producto': {
                'id': pro.id,
                'name': pro.name,
                'get_image': pro.get_image,
                'desc': pro.desc,
                'pvp': pro.pvp,
                'cate': pro.cate,
                'ingre': ingredientes,
                'agreg': agregados,
            }
        }
        listado.append(item)

    context = {'todo_prod': listado, 'categorias': categorias}
    return render(request, template_name, context)

core/erp/templates/detalles/view.html
{% extends 'list2.html' %}
{% load static %}


{% block content %}

    <div class="row">

        {% for p in productos %}

            <section id="about" class="about">
      <div class="container aos-init aos-animate" data-aos="fade-up">

        <div class="section-title">
          <h2>{{ p.producto.name }}</h2>
        </div>

        <div class="row">
          <div class="col-lg-4">
            <img src="{{ p.producto.get_image }}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8 pt-4 pt-lg-0 content">
            <h3>Ingredientes</h3>
                {% for ing in p.producto.ingre %}
                    {{ ing }}
                {% empty %}
                    <p>. . .</p>
                {% endfor %}

{#              {% if p.desc != None %}#}
{#                 <p>{{ p.desc }}</p>#}
{#              {% else %}#}
{#                 <p>Este producto no tiene descripcion . . .</p>#}
{#              {% endif %}#}

            <p class="fst-italic">
{#              Esperemos disfuten de nuestros servicios#}
            </p>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right"></i> <strong>Categoría:</strong> <span>{{ p.producto.cate }}</span></li>
                  <li><i class="bi bi-chevron-right"></i> <strong>Precio:</strong> <span>{{ p.producto.pvp }}</span></li>
{#                  <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>+123 456 7890</span></li>#}
{#                  <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>New York, USA</span></li>#}
                </ul>
              </div>
{#              <div class="col-lg-6">#}
{#                <ul>#}
{#                  <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>30</span></li>#}
{#                  <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Master</span></li>#}
{#                  <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>email@example.com</span></li>#}
{#                  <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span>Available</span></li>#}
{#                </ul>#}
{#              </div>#}
            </div>
            <p>
             Esperemos nuestras ofertas sean de su agrado. Gracias por visitarnos
            </p>
              <a href="{% url 'erp:product_list' p.producto.cate %}" type="button" class="btn btn-danger btn-block btn-sm">
                <i class="fa fa-arrow-circle-left"></i> Regresar
            </a>
          </div>
        </div>

      </div>
    </section>

{#            <div class="col-md-3 col-sm-6 col-12">#}
{#                <div class="info-box bg-info">#}
{##}
{#              <span class="info-box-icon">#}
{#                  <img src="{{ p.get_image }}"#}
{#                       class="img-fluid d-block mx-auto">#}
{#              </span>#}
{##}
{#              <div class="info-box-content">#}
{#                <span class="info-box-text">{{ p.name }}</span>#}
{#                <span class="info-box-number">$ {{ p.pvp }}</span>#}
{#                <span class="progress-description">#}
{#                  {% if p.desc != None %}#}
{#                    {{ p.desc }}#}
{#                  {% else %}#}
{#                      . . .#}
{#                  {% endif %}#}
{#                </span>#}
{#              </div>#}
{##}
{#              <a href="#" class="small-box-footer">#}
{#                <i class="fas fa-arrow-circle-right"></i>#}
{#              </a>#}
{##}
{#            </div>#}
{#            <!-- /.info-box -->#}
{#          </div>#}

    {% empty %}
            <div class="alert alert-danger alert-dismissible">
{#                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>#}
                    <h5><i class="icon fas fa-ban"></i> Upsss...</h5>
                        <h6>No se encuentra este producto en la tienda</h6>
            </div>

    {% endfor %}

</div>

{% endblock %}

{% block javascript %}
    <script>
        {#console.log(data);#}
    </script>
{% endblock %}

core/erp/templates/detalles/view_total.html
{% extends 'list2.html' %}
{% load static %}

{% block content %}

    <div class="row">

    {% for t in total_cat_pro %}
        <h3> {{ t.categ.cat }}</h3>

        {% for p in t.categ.cat_prod %}
{#                <h6>{{ p.producto }}</h6>#}
            <div class="col-md-3 col-sm-6 col-12">
                <div class="info-box bg-info">
              <span class="info-box-icon">
                  <img src="{{ p.producto.get_image }}"
                       class="img-fluid d-block mx-auto">
              </span>

              <div class="info-box-content">
                <span class="info-box-text">{{ p.producto.name }}</span>
                <span class="info-box-number">$ {{ p.producto.pvp }}</span>
                <span class="progress-description">
                    {% for ing in p.producto.ingre %}
                        {{ ing }}
                    {% empty %}
                        . . .
                    {% endfor %}
{#                    PARA DESCRIPCION#}
{#                  {% if p.producto.desc != Empty %}#}
{#                    {{ p.producto.desc }}#}
{#                  {% else %}#}
{#                      . . .#}
{#                  {% endif %}#}
                </span>
              </div>

              <a href="{% url 'erp:product_view' p.producto.id %}" class="small-box-footer">
                <i class="fas fa-arrow-circle-right"></i>
              </a>

            </div>
            <!-- /.info-box -->
          </div>

{#    {% empty %}#}
{#            <div class="alert alert-danger alert-dismissible">#}
{#                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>#}
{#                    <h5><i class="icon fas fa-ban"></i> Upsss...</h5>#}
{#                        <h6>No se encuentran productos en esta categoría</h6>#}
{#            </div>#}

    {% endfor %}


    {% endfor %}






</div>

{% endblock %}

{% block javascript %}
    <script>
        {#console.log(data);#}
    </script>
{% endblock %}