cofig/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.categorias.views import CategoryListView, listar_categorias
from core.erp.views.productos.views import ProductListView
# from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

from core.erp.views.views import IndexView, view_general, view_productos

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', IndexView.as_view(), name='index'),
    path('', view_general, name='index'),
    path('<id>/', view_productos, name='product_view')

    # path('', listar_categorias, name='index'),
    # path('erp/', include('core.erp.urls'), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.categorias.views import *
from core.erp.views.detalles.views import ver_productos
# from core.erp.views.detalles.views import ver_productos, view_general
# from core.erp.views.clientes.views import *
# from core.erp.views.dashboard.views import DashboardView
from core.erp.views.productos.views import *
# from core.erp.views.tests.views import TestView

app_name = 'erp'

urlpatterns = [

    #Catalogo
    path('', listar_categorias, name='category_list'),
    # path('detalles/<id>', ver_productos, name='product_view'),

    # path('<nombre>/', listar_productos, name='product_list'),
    # path('b', buscar_productos, name='buscar'),
    # path('detail/<id>/', ver_productos, name='product_view'),
    # path('total/general/', view_general, name='product_view_general'),


    # Categorias
    # path('categorias/list/', CategoryListView.as_view(), name='category_list'),

    # path('categorias/add/', CategoryCreateView.as_view(), name='category_create'),
    # path('categorias/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    # path('categorias/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # path('categorias/list/', search, name='category_list'),

    # path('categorias/form/', CategoryFormView.as_view(), name='category_form'),

    # Clientes
    # path('clientes/list/', ClientListView.as_view(), name='client_list'),
    # path('clientes/add/', ClientCreateView.as_view(), name='client_create'),
    # path('clientes/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    # path('clientes/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    # Productos
    # path('productos/list/', ProductListView.as_view(), name='product_list'),

    # path('productos/add/', ProductCreateView.as_view(), name='product_create'),
    # path('productos/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    # path('productos/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),


    # Home
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # Tests
    # path('test/', TestView.as_view(), name='tests'),
]

templates/todo_otro/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2020-<script>document.write(new Date().getFullYear())</script>
        <a href="">GoldenDragon</a>.</strong>
    Todos los derechos reservados.
</footer>

templates/todo_otro/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="icon" href="{% static 'img/logo.png' %}" type="image/png"/>
  <title>{{ title }}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">

{#    Admin lte theme#}
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
{#    <script src="{% static 'lib/adminlte-3.2.0/js/demo.js' %}"></script>#}

   <!-- Sweet alert -->
  <script src="{% static 'lib/sweet_alert/sweetalert2.js' %}"></script>
  <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    <link href="{% static 'lib/bootstrap-5.3.0/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'lib/bootstrap-5.3.0/js/bootstrap.bundle.min.js' %}" ></script>

  {% block head %}

  {% endblock %}
</head>
    {% block body %}
    {# AQUI ES TODO EL CUERPO#}

    {% endblock %}


</html>

templates/todo_otro/layout.html
{#{% extends 'vtc/body.html' %}#}
{% extends 'hzt/body.html' %}

templates/todo_otro/list2.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
{#    <script src="{% static 'js/jquery.min.js' %}"></script>#}
    {% comment %}<link rel="stylesheet" href="{% static 'lib/bootstrap-5.3.0/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/data_tables/css/dataTables.bootstrap4.css' %}">{% endcomment %}
    <link rel="stylesheet" href="{% static 'lib/data_tables/datatables.min.css' %}">
    <script src="{% static 'lib/data_tables/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/data_tables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/data_tables/datatables.min.js' %}"></script>
    <script src="{% static 'lib/data_tables/datatables.js' %}"></script>

    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content_body %}
      {% block content %}

      {% endblock %}
{% endblock %}


    <!-- Block javascript -->
{% block javascript %}
    <script>
        $(function (){
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });

            $('.btnTest').on('click', function (){
                $.ajax({
                    url: '{% url "erp:category_list" %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data){
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown){
                    alert(textStatus+': '+errorThrown);
                    console.log(textStatus+': '+errorThrown);
                }).always(function (data){

                });
            });
        });
    </script>
{% endblock %}